<?php


use ALoskutov\FishText\FishText;
use ALoskutov\FishText\FishTextAdaptorOnline;
use PHPUnit\Framework\TestCase;

class FishTextAdaptorOnlineTest extends TestCase
{

    public FishText $fishtext;

    /**
     * @covers ALoskutov\FishText\FishText::__construct
     * @covers ALoskutov\FishText\FishText::setFormat
     * @covers ALoskutov\FishText\FishText::getFormat
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::getFormat
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::setFormat
     * @return void
     */
    public function testFormat()
    {
        $this->fishtext->setFormat('html');
        $this->assertEquals('html', $this->fishtext->getFormat());
    }

    /**
     * @covers ALoskutov\FishText\FishText::__construct
     * @covers ALoskutov\FishText\FishText::sentence
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::createQuery
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::getRequest
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::request
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::sentence
     * @return void
     */
    public function testSentence()
    {
        $this->assertIsString( $this->fishtext->sentence());
    }

    /**
     * @covers ALoskutov\FishText\FishText::setFormat
     * @covers ALoskutov\FishText\FishText::paragraph
     * @covers ALoskutov\FishText\FishText::__construct
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::createQuery
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::getRequest
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::request
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::paragraph
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::setFormat
     * @return void
     */
    public function testParagraph()
    {
        $this->fishtext->setFormat('html');
        $this->assertIsString( $this->fishtext->paragraph());
    }

    /**
     * @covers ALoskutov\FishText\FishText::__construct
     * @covers ALoskutov\FishText\FishText::title
     * @covers ALoskutov\FishText\FishText::setFormat
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::createQuery
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::getRequest
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::request
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::setFormat
     * @covers ALoskutov\FishText\FishTextAdaptorOnline::title
     * @return void
     */
    public function testTitle()
    {
        $this->fishtext->setFormat('json');
        $this->assertIsString( $this->fishtext->title());
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->fishtext = new FishText();
    }

    public function tearDown(): void
    {
        unset($this->fishtext);
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
