<?php


use App\FishText;
use PHPUnit\Framework\TestCase;

class FishTextTest extends TestCase
{

    public FishText $fishtext;

    /**
     * @covers App\FishText::setFormat
     * @covers App\FishText::getFormat
     * @return void
     */
    public function testFormat()
    {
        $this->fishtext->setFormat('html');
        $this->assertEquals('html', $this->fishtext->getFormat());
    }

    /**
     * @covers App\FishText::sentence
     * @covers App\FishText::createQuery
     * @covers App\FishText::getRequest
     * @covers App\FishText::request
     * @return void
     */
    public function testSentence()
    {
        $this->assertIsString( $this->fishtext->sentence());
    }

    /**
     * @covers App\FishText::setFormat
     * @covers App\FishText::paragraph
     * @covers App\FishText::createQuery
     * @covers App\FishText::getRequest
     * @covers App\FishText::request
     * @return void
     */
    public function testParagraph()
    {
        $this->fishtext->setFormat('html');
        $this->assertIsString( $this->fishtext->paragraph());
    }

    /**
     * @covers App\FishText::title
     * @covers App\FishText::setFormat
     * @covers App\FishText::createQuery
     * @covers App\FishText::getRequest
     * @covers App\FishText::request
     * @return void
     */
    public function testTitle()
    {
        $this->fishtext->setFormat('json');
        $this->assertIsString( $this->fishtext->title());
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->fishtext = new FishText();
    }

    public function tearDown(): void
    {
        unset($this->fishtext);
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
