<?php


use ALoskutov\FishText\FishText;
use ALoskutov\FishText\FishTextAdaptorLocal;
use PHPUnit\Framework\TestCase;

class FishTextAdaptorLocalTest extends TestCase
{

    public FishText $fishtext;

    /**
     * @covers ALoskutov\FishText\FishText::__construct
     * @covers ALoskutov\FishText\FishText::setFormat
     * @covers ALoskutov\FishText\FishText::getFormat
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::__construct
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::getFormat
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::setFormat
     * @return void
     */
    public function testFormat()
    {
        $this->fishtext->setFormat('html');
        $this->assertEquals('html', $this->fishtext->getFormat());
    }

    /**
     * @covers ALoskutov\FishText\FishText::__construct
     * @covers ALoskutov\FishText\FishText::sentence
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::__construct
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::generator
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::sentence
     * @return void
     */
    public function testSentence()
    {
        $this->assertIsString( $this->fishtext->sentence());
    }

    /**
     * @covers ALoskutov\FishText\FishText::setFormat
     * @covers ALoskutov\FishText\FishText::paragraph
     * @covers ALoskutov\FishText\FishText::__construct
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::__construct
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::generator
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::paragraph
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::sentence
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::setFormat
     * @return void
     */
    public function testParagraph()
    {
        $this->fishtext->setFormat('html');
        $this->assertIsString( $this->fishtext->paragraph());
    }

    /**
     * @covers ALoskutov\FishText\FishText::__construct
     * @covers ALoskutov\FishText\FishText::title
     * @covers ALoskutov\FishText\FishText::setFormat
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::__construct
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::generator
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::setFormat
     * @covers ALoskutov\FishText\FishTextAdaptorLocal::title
     * @return void
     */
    public function testTitle()
    {
        $this->fishtext->setFormat('html');
        $this->assertIsString( $this->fishtext->title());
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->fishtext = new FishText(new FishTextAdaptorLocal());
    }

    public function tearDown(): void
    {
        unset($this->fishtext);
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
